### PR TITLE
Autofocus search field if width more 992px

### PR DESCRIPTION
**Pull request by andrey1s**
used the size of the desktop http://getbootstrap.com/css/#responsive-utilities

### CODE REVIEW

**Comment by alcohol** [comment]
Refs #554 #539 #309

**Comment by alcohol** [comment]
Could you please fix the codestyle though?

**Comment by andrey1s** [comment]
@alcohol fixed. could you specify the rules for the styles `js`?

**Comment by Seldaek** [comment]
That's probably safe, thanks

**Comment by frederikbosch** [comment]
Wonderful: great work. Many thanks!

**Comment by alcohol** [comment]
Just to point out, this will not work for any of the iPad retina displays for example (or any other handheld device sporting a similar resolution).

**Comment by frederikbosch** [comment]
@alcohol Then how about this. All browsers without orientation aspects get the auto focus. Others do not.

```
if(typeof window.orientation === 'undefined'){ }
```

**Comment by andrey1s** [comment]
@alcohol f this option with iPad retina doesn't fit, then another option to use [device.js](https://github.com/matthewhudson/device.js) but he adds attributes to `<html>`

**Comment by alcohol** [comment]
I was just pointing it out. I do not know how much of an issue it really is. :-)

**Comment by Seldaek** [comment]
I think @alcohol means iPads won't get the autofocus? Or do you mean they will get wrongly detected because of their high resolution? AFAIK retina uses virtual pixels for all purposes of JS/CSS and not the real device pixels.

Anyway I think it's not a problem, our mobile/tablet usage is very low. It was mostly causing issues on small mobile that had the keyboard popping up, but if it focuses or not on ipad does not matter I think.

**Pull request merged**
