### PR TITLE
Update SymlinkDumper.php

### PR DESCRIPTION
**Pull request by bdaler**
заебал это гавно! мудаки вы конченные!

### CODE REVIEW

**Comment by uuf6429** [comment]
@bdaler so let's get this straight, the one and only public "contribution" you do is to follow your government in threatening people. Good job showing the world what peace means. :)

And by the way, if you didn't get it, when people say they stand with Ukraine it means they stand with Ukrainian's right to their territory, and not all your alleged "nazis" - in the same way that people sympathise with Russians sent to the front as cannon fodder, thanks to your sick imperialist government.

I'm pretty sure you're far gone with your government's lies and fantasies, but here's a thought anyway - if Russia wanted to be the hero, why march to Kyiv and annex territories illegally, when they could have evacuated all those "poor oppressed Russians/Ukrainians" you're talking about? Maybe that hack of a Russian troll @Gemorroj or naive St-Peterburger-that-knows-all-about-Ukraine @politsin might want to chime in? You can never get your company enough favours from the government, right?

----

This message stays, not because we care about your corrupt government (from the very top), but to celebrate and inspire Ukrainians everywhere that we're with them.

**Comment by politsin** [comment]
wow! personal mention)

The message is in Russian, but it has stylistic errors, because bdaler lives in Tajikistan.

He and his government are not a party to the conflict, unlike the "light democracies of Europe". But he must watch the messages in his console and be annoyed.

@dbaler - switch the composer to Chinese servers, they are free and independent unlike @Seldaek's head

**Comment by uuf6429** [comment]
> wow! personal mention)
> 
> The message is in Russian, but it has stylistic errors, because bdaler lives in Tajikistan.
> 
> He and his government are not a party to the conflict, unlike the "light democracies of Europe". But he must watch the messages in his console and be annoyed.

Nope, he's in Udmurtia, a federal subject of Russia.
Or is this where you tell me Russia annexes countries, throws in a puppet government and then calls it an "independent" "sovereign" republic? 😉

**Comment by politsin** [comment]
🤦‍♂️

**Pull request closed without merging**
