### PR TITLE
feat(peace): remove #StandWithUkraine

### PR DESCRIPTION
**Pull request by bl0cknumber**
We don't want this to be on the CLI screen. Everyone wants peace, but the writing #StandWithUkraine supports one side. This word hurts the feelings of the Russian people who don't want war. We can achieve peace if we side with both sides, regardless, and that's why there is such a thing as negotiation in the political world. This article is very annoying and makes me not want to use composer. You should apologize or delete it for writing this.

I would suggest you should write this on the Repository instead of CLI.

Let's keep the CLI neutral. 

#NoStandJustUnderstandEachOther
#NeutralComposerCLI

rel: https://github.com/composer/packagist/pull/1267#issuecomment-1063636569

### CODE REVIEW

**Comment by bl0cknumber** [comment]
I would suggest you should write this on the Repository instead of CLI.

**Comment by bl0cknumber** [comment]
lets keep the CLI neutral.

**Comment by lwlwilliam** [comment]
> We don't want this to be on the CLI screen. Everyone wants peace, but the writing #StandWithUkraine supports one side. This word hurts the feelings of the Russian people who don't want war. We can achieve peace if we side with both sides, regardless, and that's why there is such a thing as negotiation in the political world. This article is very annoying and makes me not want to use composer. You should apologize or delete it for writing this.
> 
> I would suggest you should write this on the Repository instead of CLI.
> 
> Let's keep the CLI neutral.
> 
> #NoStandJustUnderstandEachOther #NeutralComposerCLI
> 
> rel: [#1267 (comment)](https://github.com/composer/packagist/pull/1267#issuecomment-1063636569)

Friend, haven't you seen through these hypocritical people? They don't really stand with Ukraine. They just want to carve up Russia. You can see their attitude towards Palestine. They never dare to stand with Palestine.

**Comment by naderman** [comment]
Who is being hurt or rather often killed right now are civilians in Ukraine. That needs to end urgently.

**Pull request closed without merging**
