### PR TITLE
Added JSONP support to search

### PR DESCRIPTION
**Pull request by rdohms**
`/search.jsonp?q=something&callback=my_call`

Will return a valid JSONP response that can be read from a JS call.

### CODE REVIEW

**Comment by stof** [comment]
``/search.jsonp`` looks weird to me. Why not keeping ``search.json?callback=my_call``, which would also keep the whole logic much simpler ?

Btw, your commit appear to be done by a user named ``travis-ci`` with an email not associated with your account. Is it expected ?

**Comment by rdohms** [comment]
Ah dang.... i messed up my config it seems.

As for json or jsonp, i'm not sure what standard practice is, i can go either way.

**Comment by rdohms** [comment]
@stof I do see here some implementations doing that, only adding the callback parameter. I'll adjust this and open a new PR

**Comment by stof** [comment]
Well, you could just update this PR though rather than opening a new one

**Pull request closed without merging**
