### PR TITLE
[RFC][WIP] Redesign of packagist.org

### PR DESCRIPTION
**Pull request by stloyd**
Hey,

from start I would say that I love the idea of composer + packagist, also I really love FOSS. I use quite often the packagist.org page, and I must say that I have some parts missing, yet some parts I recognize as not best from UI look (I'm not a designer, just simple user =) so not kill me too fast for those words =)), so I decided to give some of my free time to create this proposal, which is kinda prototype, but IMO it's at least a bit more usable =)

Let me give some details below, and decide what to do, I mean, should it be official or not? =)

After some comments from people after showing the sneak peak:

sneak peak

I'm showing my work here, to have comments, disscussion, bashing or whatever :panda_face: 

Right now at this PR last version of header is used:

headers

Here is really simple TODO list for pages/macros not redesigned:
- [x] homepage
- [x] edit profile
- [x] change password
- [x] my profile
- [x] list of packages
- [x] search page (results - bases on above)
- [x] my packages (bases on above)
- [x] my favourite packages (bases on above)
- [ ] package page (bases on above)
- [ ] vendor page (bases on above)
- [x] popular packages (bases on above)
- [x] explore (bases on above)
- [x] browse (bases on above)
- [x] show profile
- [x] login
- [x] register
- [x] remind password
- [x] error page
- [x] statistics
- [x] submit package
- [x] about
- [x] feed

Additional TODO list:
- [ ] port javascript to new version
- [ ] clean up images/fonts/css files
- [x] update to Bootstrap 3

_I could miss something in that list or duplicate, sorry for that =)_

### CODE REVIEW

**Comment by philsturgeon** [comment]
*Post-Holidays Bump*

**Comment by tristanlins** [comment]
I'm still here, but before feb/march I have no time for the rebase :-\

**Comment by venyii** [comment]
Hey guys, I took some time and tried to rebase from master. It´s at https://github.com/venyii/packagist/tree/feature/redesign. This will hopefully help!

The statistics page currently has both chart types (old and new) since I have no real test data to display anything to decide which one´s looking better.

As mentioned in the PR, some pages are still missing (package, ...), responsive is working fairly well, although there´s still a bit of work left (navigation for example). I replaced some hard-coded values (username in menues, gravatar image in top bar).

ping @Seldaek

**Comment by tristanlins** [comment]
@venyii I take a short review, looks good :-)

**Comment by davidgorges** [comment]
Looks really cool. I would love to see that merged, too.

**Comment by garak** [comment]
:+1:

**Comment by Seldaek** [comment]
Just so everyone knows and nobody wastes time rebasing once more, I have an integration branch here with the redesign merged with master that is getting close to ready. I put a lot of finishing touches and cleanup here and there, and there is only the package page left to finalize before I can go live with this.

**Comment by rdohms** [comment]
That is awesome news @Seldaek thank you for that!

**Comment by PeeHaa** [comment]
Awesomesauce @Seldaek!

**Comment by Seldaek** [comment]
It's live!

**Comment by philsturgeon** [comment]
gamera turtle

**Comment by philsturgeon** [comment]
The site is _really_ slow at the moment. I'm guessing it's related. Any ideas?

**Comment by Seldaek** [comment]
Yeah the speed seems to be related to one of the boatload of dependencies I updated earlier today.. Not sure which but something isn't happy so I rolled back those changes and we're back on track :)

**Comment by carlosbuenosvinos** [comment]
Good job guys! Congrats!

**Comment by sdiaz** [comment]
really nice, congrats!

**Comment by jaypatel512** [comment]
Looks amazing ! :+1:

**Comment by stof** [comment]
just a small remark: it is more common to have the name of the logged in user (with a dropdown to access the profile and a few other pages) on the right of the topbar than in the middle. Changing the order of items might be a good idea.

**Comment by mvdkleijn** [comment]
Looks amazing @Seldaek!

One minor niggle: the green show api token button flows over / on top of the sticky menu bar while its related input field flows under like it should. On mobile chrome.

**Comment by tristanlins** [comment]
giphy

**Pull request closed without merging**
