### PR TITLE
Enabled CORS for API URLs

### PR DESCRIPTION
**Pull request by javiereguiluz**
As discussed in #588.

### CODE REVIEW

**Comment by stof** [comment]
you are misisng the update of the AppKernel to rgister the bundle

**Comment by javiereguiluz** [comment]
Updated. Thanks!

**Comment by Seldaek** [comment]
Thanks, note that the regexes don't need to escape `/`s (fixed in commit above) :)

**Comment by javiereguiluz** [comment]
Thanks for merging and sorry for the regexp error.

**Comment by Seldaek** [comment]
Well no biggie they were not errors per se just unneeded/superfluous 
escaping so I thought I'd let you know :)

**Pull request merged**
