### PR TITLE
Add #StandWithPalestine banner to updates 🟥🟩

### PR DESCRIPTION
**Pull request by azjezz**

### CODE REVIEW

**Comment by lwlwilliam** [comment]
I'm glad someone still remembers this incident. A few days after the attack, the author had quietly removed that piece of shit information. Is it a coincidence?

**Comment by Seldaek** [comment]
Sorry but nope. Please stop asking for banners. We don't take requests.

**Comment by azjezz** [comment]
I had no intention for this PR to actually get merged, just wanted to highlight the double standard here. When civilians were dying in Ukraine, Composer showed support with a banner, and I respect that. Now, when it's Palestine, the response is different.

I get it, Composer isn’t a political platform. But, it's disheartening to see the selective empathy especially when the tech community has the power to raise awareness on serious issues.

Since opening this PR, more children have died in Gaza than all civilian casualties in Ukraine over the past month. In fact, the number of people who have died in Gaza in the past 17 days equals [the civilian casualties in the Ukraine war over the past year and a half](https://www.ohchr.org/en/news/2023/09/ukraine-civilian-casualty-update-11-september-2023). This really puts things into perspective.

**Comment by nvelychenko** [comment]
Hey dude, when Palestinians go to Israel and burn children alive it's okay, but when Israel responds it's not. I'm not sure why someone ever should stand with Palestine if it should be StandWithIsrael.

**Pull request closed without merging**
