### PR TITLE
[WIP] Emoji in package name

### PR DESCRIPTION
**Pull request by WyriHaximus**
Gather round, gather round and let me tell you a tale on Hallows eve. A tale about adding support for package names with emoji in them.

It all started when a lone developer wanted to add a package named `wyrihaximus/☼` but packagist wouldn't let him. The developer was disappointed but decided to dive into the horrors of `UTF-8` and found it how hard it would be to add this as a feature. He realised `composer` would also need a PR but decided to seek guidance of the packagist high council of wizards, witches, and other magical beings first, before embarking on his quest.

The council listened to his plan. He explained that while `UTF-8` is dangerous and has wacky controll characters that can do serious harm, only allowing certain ranges would slay that dragon. The question is what ranges to allow, only emoji, or also chinese, russian, and other languages. Where to draw the line. He hands over a an quick rough drawing of his plan and sits down waiting for a response from the council.

♪ Waiting medival flute music ♪

### CODE REVIEW

**Comment by alcohol** [comment]
GO AWAY CEES-JAN

**Comment by alcohol** [comment]
Just kiddin', we can still be friends. But eh, see #608

**Comment by alcohol** [comment]
As you can see in that PR, we do allow utf8 in some attributes (very reluctantly). I cannot in good conscience back this PR though. Allowing this for package names, well, this is a very special can of worms that I think should never be opened. And honestly, other than for the sake of novelty it serves no purpose whatsoever. I have to vote :-1: on this, sorry bud.

**Comment by WyriHaximus** [comment]
> Just kiddin', we can still be friends. But eh, see #608

Yeah noticed that issue and the fixing commit. Did my research and also know you don't take any database changes lightly.

> Allowing this for package names, well, this is a very special can of worms that I think should never be opened. And honestly, other than for the sake of novelty it serves no purpose whatsoever.

Honestly that is pretty much the reason I personally would like it. But I can see the use for non-latin character use for naming package in other languages.

> I have to vote :-1: on this, sorry bud. 

No need  to apologize I know this was a very very very long shot from the start. For any of the following points, and probably more from your side I don't ever see right now:

- UTF-8 in all it's awesomeness is a huge can of worms with with certain control and whitespace characters
- Not only has packages has to be updated, composer also has to be able to handle it.
- My own IDE (PHPStorm) isn't even capable is [displaying](https://github.com/WyriHaximus/packagist/commit/2051ff71720b54d1e7a6ea6c531cabb0fd7b9f13) all characters properly, neither are my browsers 
- Not only accepting a package has to be updated but also displaying the emoji every where correctly
- Display the raw or use an image to display it on the site
- When removing control characters combining emoji isn't possible, which is going to raise questions
- Problems in command lines, IDE's text editors, etc etc etc (Hack using a ☼ as namespace is going to be funky at the very least.)

**Comment by Seldaek** [comment]
Yeah I think we'll have to decline this, I'm sure it'd allow for fun times but  I also can't imagine the amount of time wasted fixing weird bugs that will crop up everywhere, so please no :)

**Comment by WyriHaximus** [comment]
No worries, I completely understand :)

**Comment by stof** [comment]
this would be very hard for package names btw, because they end up being used in filesystem paths, where UTF-8 support is not cross-platform

**Pull request closed without merging**
