### PR TITLE
Move tags below package name

### PR DESCRIPTION
**Pull request by ADmad**
Before:
packagist-before

After:
packagist-after

### CODE REVIEW

**Comment by dereuromark** [comment]
:+1:

**Comment by dakota** [comment]
That looks way better! :+1:

**Comment by Casmo** [comment]
:thumbsup:

**Comment by hmic** [comment]
:thumbsup:

**Comment by beporter** [comment]
:+1: because of this:

packagist_tags_truncated

**Comment by josegonzalez** [comment]
:+1:

**Comment by sizuhiko** [comment]
:+1:

**Comment by hkdobrev** [comment]
:+1: Yaay! :star2:

**Comment by jadb** [comment]
:+1:

**Comment by lorenzo** [comment]
Nice! :+1:

**Comment by Swader** [comment]
:+1:

**Comment by Seldaek** [comment]
This is made irrelevant by https://github.com/composer/packagist/pull/331#issuecomment-108573100 so I'm closing the +1 firehose..

**Comment by ADmad** [comment]
Nice,  awaiting the unveiling of new design.

**Pull request closed without merging**
